In [22]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip available: 22.3.1 -> 23.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np
np.__version__

'1.24.2'

###Membandingkan kecepatan antara numpy dengan list core python###

In [24]:
b = list(range(10))
print(b)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [25]:
#code function sum menggunakan list
#menambahkan list a dan list b dari jumlah range sebagai inputan
def python_listsum(n):
    a = b = list(range(n)) #menginisialisasi a dan b dari list range
    hasil = []
    for idx in range(len(a)):
        x = a[idx] ** 2
        y = b[idx] ** 3
        hasil.append(x+y)
    
    return hasil

In [26]:
hasil_listsum = python_listsum(10)
print(hasil_listsum)

[0, 2, 12, 36, 80, 150, 252, 392, 576, 810]


In [27]:
def numpy_sum(n):
    x = np.arange(n) ** 2
    y = np.arange(n) ** 3
    return x+y

In [28]:
hasil = numpy_sum(10)
print(hasil)

[  0   2  12  36  80 150 252 392 576 810]


In [29]:
#kita bandingkan dengan waktu menggunakan lib datetime
from datetime import datetime
size = 1000000
awal = datetime.now()
#call func
akhir = datetime.now() - awal
print(f"Waktu yang dibutuhkan : {akhir.microseconds}")
print(f"Data 2 akhir dari list : {hasil[-2:]}")

Waktu yang dibutuhkan : 0
Data 2 akhir dari list : [576 810]


In [30]:
from datetime import datetime
size = 1000000
awal = datetime.now()
#call func
akhir = datetime.now() - awal
print(f"Waktu yang dibutuhkan : {akhir.microseconds}")
print(f"Data 2 akhir dari list : {hasil[-2:]}")

Waktu yang dibutuhkan : 0
Data 2 akhir dari list : [576 810]


In [31]:
print(np.__doc__)


NumPy
=====

Provides
  1. An array object of arbitrary homogeneous items
  2. Fast mathematical operations over arrays
  3. Linear Algebra, Fourier Transforms, Random Number Generation

How to use the documentation
----------------------------
Documentation is available in two forms: docstrings provided
with the code, and a loose standing reference guide, available from
`the NumPy homepage <https://numpy.org>`_.

We recommend exploring the docstrings using
`IPython <https://ipython.org>`_, an advanced Python shell with
TAB-completion and introspection capabilities.  See below for further
instructions.

The docstring examples assume that `numpy` has been imported as ``np``::

  >>> import numpy as np

Code snippets are indicated by three greater-than signs::

  >>> x = 42
  >>> x = x + 1

Use the built-in ``help`` function to view a function's docstring::

  >>> help(np.sort)
  ... # doctest: +SKIP

For some objects, ``np.info(obj)`` may provide additional help.  This is
particularly 

Create an Ndarrays

In [32]:
import numpy as np

listrange = list(range(5))
print(listrange)
print(type(listrange))

[0, 1, 2, 3, 4]
<class 'list'>


In [33]:
nparr = np.array(listrange)
print(nparr)
print(type(nparr))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [34]:
print(np.arange(5)) #start default = 0, stop, step default = 1

print(np.arange(1,9)) #star default = 1, stop = 9, step default = 1

print(np.arange(1,15,2)) #star default = 1, stop = 15, step default = 2

[0 1 2 3 4]
[1 2 3 4 5 6 7 8]
[ 1  3  5  7  9 11 13]


===================================

Add, remove, sort

In [36]:
nparr = np.arange(1,11)
print(nparr)
print(type(nparr))

[ 1  2  3  4  5  6  7  8  9 10]
<class 'numpy.ndarray'>


In [37]:
#code 
new_np = np.append(nparr, [12,14])
print(new_np)

[ 1  2  3  4  5  6  7  8  9 10 12 14]


In [38]:
del_np = np.delete(new_np, 4)
print(del_np)

[ 1  2  3  4  6  7  8  9 10 12 14]


In [39]:
np.sort?

Signature: np.sort(a, axis=-1, kind=None, order=None)
Docstring:
Return a sorted copy of an array.

Parameters
----------
a : array_like
    Array to be sorted.
axis : int or None, optional
    Axis along which to sort. If None, the array is flattened before
    sorting. The default is -1, which sorts along the last axis.
kind : {'quicksort', 'mergesort', 'heapsort', 'stable'}, optional
    Sorting algorithm. The default is 'quicksort'. Note that both 'stable'
    and 'mergesort' use timsort or radix sort under the covers and, in general,
    the actual implementation will vary with data type. The 'mergesort' option
    is retained for backwards compatibility.

    .. versionchanged:: 1.15.0.
       The 'stable' option was added.

order : str or list of str, optional
    When `a` is an array with fields defined, this argument specifies
    which fields to compare first, second, etc.  A single field can
    be specified as a string, and not all fields need be specified,
    but unspecif

In [41]:
random_array = np.array([4,2,1,10,3,9,7,6,5,8])
pengurutan = np.sort(random_array)
print(pengurutan)

[ 1  2  3  4  5  6  7  8  9 10]


Multi Dimensional Arrays

In [43]:
multiplelist = [[0,1,2,3],[10,11,12,13]]
print(multiplelist)

np_arr = np.array(multiplelist)
print(f"Numpy array 2D : {np_arr}")
print(f"ndim :{np_arr.ndim}, shape :{np_arr.shape}, size :{np_arr.size}")

[[0, 1, 2, 3], [10, 11, 12, 13]]
Numpy array 2D : [[ 0  1  2  3]
 [10 11 12 13]]
ndim :2, shape :(2, 4), size :8


Contoh 3D Array

In [44]:
np_arr3  = np.array(
    [
        [[0,1,2,3],[4,5,6,7]],
        [[8,9,10,11],[12,13,14,15]],
        [[16,17,18,19],[20,21,22,23]],
    ]
)
print(np_arr3)
print(np_arr3.shape)
print(np_arr3.size)
print(np_arr3.ndim)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]

 [[16 17 18 19]
  [20 21 22 23]]]
(3, 2, 4)
24
3


In [45]:
array_2d = [[0,1,2,3],[10,11,12,13]]
np_arr2d = np.array(array_2d)
print(np_arr2d)

[[ 0  1  2  3]
 [10 11 12 13]]


In [46]:
print(np_arr2d[1,3])
np_arr2d[1,3]=1
print(np_arr2d)

13
[[ 0  1  2  3]
 [10 11 12  1]]


Sorting array

In [47]:
field_mhs = [('Name','S10'),('ipk',float),('Umur',int)]
print(field_mhs)

[('Name', 'S10'), ('ipk', <class 'float'>), ('Umur', <class 'int'>)]


In [54]:
value_mhs = [('Wiguna',3.8,21),('Rizkina',3.9,21),('Yanas',3.6,22),('Hayyuni',3.7,20)]
print(value_mhs)

[('Wiguna', 3.8, 21), ('Rizkina', 3.9, 21), ('Yanas', 3.6, 22), ('Hayyuni', 3.7, 20)]


In [56]:
data_mhs = np.array(value_mhs, dtype=field_mhs)
print(data_mhs)

[(b'Wiguna', 3.8, 21) (b'Rizkina', 3.9, 21) (b'Yanas', 3.6, 22)
 (b'Hayyuni', 3.7, 20)]


In [57]:
data_sortby_name = np.sort(data_mhs, order='Name')
print(data_sortby_name)

[(b'Hayyuni', 3.7, 20) (b'Rizkina', 3.9, 21) (b'Wiguna', 3.8, 21)
 (b'Yanas', 3.6, 22)]


In [58]:
data_sortby_umuripk = np.sort(data_mhs, order=['ipk','Umur'])
print(data_sortby_umuripk)

[(b'Yanas', 3.6, 22) (b'Hayyuni', 3.7, 20) (b'Wiguna', 3.8, 21)
 (b'Rizkina', 3.9, 21)]


Zeroes
Ones

In [61]:
np.zeros(10)


array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [62]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [63]:
np.zeros((2,2,2))

array([[[0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.]]])

Reshape

In [66]:
datax = np.arange(6)
print(datax)
print(datax.shape)

[0 1 2 3 4 5]
(6,)


In [65]:
hasil_reshape = datax.reshape(2,3)
print(hasil_reshape)
print(hasil_reshape.shape)

[[0 1 2]
 [3 4 5]]
(2, 3)


In [67]:
hasil_reshape_b = datax.reshape(3,2)
print(hasil_reshape_b)
print(hasil_reshape_b.shape)

[[0 1]
 [2 3]
 [4 5]]
(3, 2)


In [68]:
hasil_reshape_b = datax.reshape(3,3)
print(hasil_reshape_b)
print(hasil_reshape_b.shape)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [69]:
datay = np.arange(5)
print(datay)
res_y = datay.reshape(2,2)
print(res_y)

[0 1 2 3 4]


ValueError: cannot reshape array of size 5 into shape (2,2)

Convert 1D to 2D

In [70]:
datad = np.arange(2,8)
print(datad)
print(datad.shape)
print(datad.ndim)

[2 3 4 5 6 7]
(6,)
1


In [72]:
new_datad = datad[np.newaxis]
print(new_datad)
print(new_datad.shape)
print(new_datad.ndim)

[[2 3 4 5 6 7]]
(1, 6)
2


In [73]:
vector = datad[np.newaxis, : ]
print(vector)
print(vector.shape)

[[2 3 4 5 6 7]]
(1, 6)


In [74]:
vector_col = datad[:, np.newaxis]
print(vector_col)
print(vector_col.shape)
print(vector_col.ndim)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]
(6, 1)
2


indexing dan slicing

In [75]:
datan = np.array([0,1,2,3,4,5,6,7,8,9])
print(datan)

[0 1 2 3 4 5 6 7 8 9]


In [76]:
print(datan[1])
print(datan[-1])

1
9


In [77]:
print(datan[1:5])
print(datan[-2:])

[1 2 3 4]
[8 9]


Membuat subset atau mengiris dari array dengna menggunakan kondisi tertentu

In [79]:
list2d = [[0,1,2,3],[4,5,6,7],[8,9,10,11]]
np2d = np.array(list2d)
print(np2d)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [80]:
#ambil nilai kurang dari 6
print(np2d[np2d<6])

[0 1 2 3 4 5]


In [82]:
#ambil nilai lebih dari 7
lebihdari7 = (np2d > 7)
print(np2d[lebihdari7])

[ 8  9 10 11]


In [83]:
duakondisi = (np2d > 3) & (np2d < 7)

In [84]:
print(np2d[duakondisi])

[4 5 6]


In [88]:
print(np2d[np2d % 2 == 1])

[ 1  3  5  7  9 11]


In [89]:
np_arr1 = np.array([1,2,3,4,5,6,7,8,9,10])
print(np_arr1[4:9])

[5 6 7 8 9]


In [90]:
np_a2d = np.array([[1,1],[2,2]])
np_b2d = np.array([[3,3],[4,4]])
print(np_a2d)
print(np_b2d)

[[1 1]
 [2 2]]
[[3 3]
 [4 4]]


In [91]:
npv = np.vstack((np_a2d, np_b2d))
print(npv)

[[1 1]
 [2 2]
 [3 3]
 [4 4]]


In [92]:
npv = np.hstack((np_a2d, np_b2d))
print(npv)

[[1 1 3 3]
 [2 2 4 4]]


In [93]:
a = np.array([[1,2,3,4,5,6,7,8,9,10],[11,12,13,14,15,16,17,18,19,20]])
print(a)

[[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]


In [99]:
split = np.hsplit(a,5)
print(split)
print(type(split))

[array([[ 1,  2],
       [11, 12]]), array([[ 3,  4],
       [13, 14]]), array([[ 5,  6],
       [15, 16]]), array([[ 7,  8],
       [17, 18]]), array([[ 9, 10],
       [19, 20]])]
<class 'list'>


copying

In [101]:
x = [0,1]
y = [2,3]
z = x
print(x)
print("##"*10)
z[0] = 10
print(z)

[0, 1]
####################
[10, 1]


In [102]:
newy = y.copy()
newy[0] = 100
print(newy)
print(y)

[100, 3]
[2, 3]


Basic Array Operator

In [103]:
np1d = np.array([1,2,3,4,5,6,7,8])
print(np1d.sum())

36


In [106]:
np2da = np.array([[10,20],[30,40]])
print(np2da)
print("#"*10) 
print(np2da.sum(axis = 0)) #menjumlahkan baris
print("#"*10) 
print(np2da.sum(axis = 1)) #menjumlahkan kolom

[[10 20]
 [30 40]]
##########
[40 60]
##########
[30 70]


In [107]:
data_b = np.array([1,2])
new_datab = data_b * 1.6
print(new_datab)


[1.6 3.2]


Function bawaan numpy

###random

In [110]:
randomdata = np.random.randint(30)
print(randomdata)

7


In [112]:
np.random.seed(0)
randomdata = np.random.randint(30)
print(randomdata)

12


In [114]:
print(np.random.randint(10,30,8))

[25 10 13 13 17 19 29 28]


In [118]:
np.random.seed(2)
print(np.random.randint(5,high = 20, size=(2,3)))


[[13 18 13]
 [11 16  7]]


Array Operation

In [119]:
print(np1d)

[1 2 3 4 5 6 7 8]


In [122]:
print(np1d.max())
print(np1d.min())
print(np1d.sum())

8
1
36


In [124]:
print(np2da)
print(np2da.min())
print(np2da.max())
print(np2da.sum())

[[10 20]
 [30 40]]
10
40
100


In [127]:
data_arr = np.array([[0.12345678,1.23456789,2.34567890,3.45678912],
         [0.12345678,1.23456789,2.34567890,3.45678912],
         [0.12345678,1.23456789,2.34567890,3.45678912]]
         )
print(data_arr)

[[0.12345678 1.23456789 2.3456789  3.45678912]
 [0.12345678 1.23456789 2.3456789  3.45678912]
 [0.12345678 1.23456789 2.3456789  3.45678912]]


In [128]:
np.save("my_numpy_arr,py",data_arr)

Matrix

In [129]:
matriks = np.array([[1,2],[4,5],[6,7]])
print(matriks)

[[1 2]
 [4 5]
 [6 7]]


In [ ]:
matriks_ones = np.ones(2,2)


In [133]:
data_m = np.array([[1,2],[3,4],[5,8]])
print(data_m)
print("+"*10)
print(data_m[0,1]) #baris ke 0 kolom ke 1
print(data_m[1:3]) #baris ke 1 sampai 3

[[1 2]
 [3 4]
 [5 8]]
++++++++++
2
[[3 4]
 [5 8]]


Matriks Aritmatika

In [3]:
data = np.array([[1,2],[3,4]])
print(data)

[[1 2]
 [3 4]]


In [4]:
ones = np.ones([2,2])
print(ones)

[[1. 1.]
 [1. 1.]]


In [5]:
print(data + ones)

[[2. 3.]
 [4. 5.]]


In [6]:
ones_row = np.ones([1,2])
print(ones_row)

[[1. 1.]]


In [8]:
print(data + ones_row)

[[2. 3.]
 [4. 5.]]


Dot Product

In [9]:
a_1 = np.array([[1,2,3],[4,5,6]])
print(a_1)
print(a_1.shape)

a_2 = np.array([[7,8],[9,10],[11,12]])
print(a_2)
print(a_2.shape)

[[1 2 3]
 [4 5 6]]
(2, 3)
[[ 7  8]
 [ 9 10]
 [11 12]]
(3, 2)


In [10]:
np.dot(a_1,a_2)

array([[ 58,  64],
       [139, 154]])

Matriks Indexing

In [11]:
data = np.array([[1,2],[3,4],[5,6]])
print(data)
print('============')
print(data[0])
print(data[1])
print(data[2])
print('============')
print(data[0,1])
print(data[1:3])
print(data[0:2,1])

[[1 2]
 [3 4]
 [5 6]]
[1 2]
[3 4]
[5 6]
2
[[3 4]
 [5 6]]
[2 4]


Matriks Aggregation

In [12]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [13]:
print(data.max())
print(data.min())
print(data.sum())

6
1
21


In [15]:
print(data.max(axis=0))
print(data.max(axis=1))

[5 6]
[2 4 6]


Transposing dan reshaping

In [16]:
print(data)

[[1 2]
 [3 4]
 [5 6]]


In [17]:
print(data.T)

[[1 3 5]
 [2 4 6]]


In [18]:
data_col = np.array([[1,2,3,4,5,6]]).T
print(data_col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]]


In [19]:
data_col.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [20]:
data_col.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [21]:
arr = np.arange(6).reshape((2,3))
print(arr)

[[0 1 2]
 [3 4 5]]


N DImensional Array

In [22]:
ndarr = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(ndarr)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [23]:
print(np.ones((4,3,2)))

[[[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]
  [1. 1.]]]


In [24]:
print(np.zeros((4,3,2)))

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]]


In [26]:
print(np.random.random((4,3,2)))

[[[4.08053527e-01 4.35069455e-02]
  [6.71465483e-02 2.29005669e-01]
  [7.96968522e-01 5.06316028e-04]]

 [[3.79911338e-01 6.60891245e-01]
  [5.39216392e-01 5.01852246e-02]
  [7.24001063e-01 3.08086554e-01]]

 [[2.00551345e-01 2.60778150e-01]
  [6.26266080e-02 7.01337614e-01]
  [9.12397133e-01 3.99549410e-01]]

 [[2.86290625e-01 4.57946682e-01]
  [8.22031337e-01 5.63858652e-01]
  [5.29711300e-01 2.59048043e-01]]]
